name: CI to ECR

on:
  workflow_dispatch:  # ✅ 수동 실행을 위해 추가
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set commit SHA as IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: |
          docker build -t algoreview/be:${{ env.IMAGE_TAG }} .
          docker tag algoreview/be:${{ env.IMAGE_TAG }} 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/be:${{ env.IMAGE_TAG }}

      - name: Push to ECR
        run: |
          docker push 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/be:${{ env.IMAGE_TAG }}
